name: Run Tests
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm i -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm i -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm i -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run typecheck